name:                learning-sbv-smt
version:             0.1.0.0
github:              "joelwikstrom/learning-sbv-smt"
license:             BSD3
author:              "Joel Wikström"
maintainer:          "joel@selectstjarna.se"
copyright:           "Joel Wikström"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            testellernåt

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joelwikstrom/learning-sbv-smt#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  learning-sbv-smt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-sbv-smt

tests:
  learning-sbv-smt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-sbv-smt
